rules:
  # Triangle Intelligence Platform - Anti-Hardcoding Rules

  - id: hardcoded-country-codes
    pattern-either:
      - pattern: |
          '$X' = 'MX'
      - pattern: |
          '$X' = 'US'
      - pattern: |
          '$X' = 'CA'
      - pattern: |
          country: 'MX'
      - pattern: |
          country: 'US'
      - pattern: |
          country: 'CA'
    message: "Hardcoded country codes detected - use configuration instead"
    languages: [javascript, typescript]
    severity: ERROR

  - id: hardcoded-tariff-rates
    pattern-either:
      - pattern: |
          $RATE = 6.8
      - pattern: |
          $RATE = 0.068
      - pattern: |
          rate: $NUM
      - pattern: |
          tariff_rate: $NUM
    message: "Hardcoded tariff rates detected - must come from database"
    languages: [javascript, typescript]
    severity: ERROR

  - id: hardcoded-company-names
    pattern-either:
      - pattern: |
          'Tropical Harvest Processors'
      - pattern: |
          "Tropical Harvest Processors"
      - pattern: |
          company_name: '$COMPANY'
    message: "Hardcoded company names detected - use user input data"
    languages: [javascript, typescript]
    severity: ERROR

  - id: hardcoded-trade-volumes
    pattern-either:
      - pattern: |
          $VOL = 1000000
      - pattern: |
          $VOL = 500000
      - pattern: |
          trade_volume: $NUM
    message: "Hardcoded trade volumes detected - use user workflow data"
    languages: [javascript, typescript]
    severity: ERROR

  - id: hardcoded-hs-codes
    pattern-either:
      - pattern: |
          '$CODE' = '8517.62.00'
      - pattern: |
          '$CODE' = '2009110111'
      - pattern: |
          hs_code: '$CODE'
    message: "Hardcoded HS codes detected - use classification API"
    languages: [javascript, typescript]
    severity: ERROR

  - id: inline-styles-react
    pattern-either:
      - pattern: |
          style={{$STYLE}}
      - pattern: |
          style="$STYLE"
    message: "Inline styles forbidden - use existing CSS classes from globals.css"
    languages: [javascript, typescript]
    severity: ERROR

  - id: tailwind-classes
    pattern-either:
      - pattern: |
          className="$...bg-$REST"
      - pattern: |
          className="$...text-$REST"
      - pattern: |
          className="$...p-$REST"
      - pattern: |
          className="$...m-$REST"
    message: "Tailwind CSS classes forbidden - use existing custom CSS"
    languages: [javascript, typescript]
    severity: ERROR